{"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":20717,"status":"ok","timestamp":1651381302284,"user":{"displayName":"Shwetanshu Sood","userId":"05007702121445912457"},"user_tz":-330},"id":"-I0STEVutgVr","outputId":"f95a0e73-57b8-4aaa-9700-dd191a9727b9"},"outputs":[{"output_type":"stream","name":"stdout","text":["\u001b[K     |████████████████████████████████| 10.1 MB 8.7 MB/s \n","\u001b[K     |████████████████████████████████| 4.3 MB 49.1 MB/s \n","\u001b[K     |████████████████████████████████| 76 kB 4.8 MB/s \n","\u001b[K     |████████████████████████████████| 164 kB 46.8 MB/s \n","\u001b[K     |████████████████████████████████| 111 kB 55.7 MB/s \n","\u001b[K     |████████████████████████████████| 181 kB 55.0 MB/s \n","\u001b[K     |████████████████████████████████| 63 kB 1.5 MB/s \n","\u001b[K     |████████████████████████████████| 131 kB 44.0 MB/s \n","\u001b[K     |████████████████████████████████| 428 kB 48.7 MB/s \n","\u001b[K     |████████████████████████████████| 130 kB 43.9 MB/s \n","\u001b[K     |████████████████████████████████| 793 kB 38.0 MB/s \n","\u001b[K     |████████████████████████████████| 381 kB 45.4 MB/s \n","\u001b[?25h  Building wheel for blinker (setup.py) ... \u001b[?25l\u001b[?25hdone\n","\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n","jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 3.0.29 which is incompatible.\n","google-colab 1.0.0 requires ipykernel~=4.10, but you have ipykernel 6.13.0 which is incompatible.\n","google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.33.0 which is incompatible.\n","google-colab 1.0.0 requires tornado~=5.1.0; python_version >= \"3.0\", but you have tornado 6.1 which is incompatible.\u001b[0m\n"]}],"source":["!pip install streamlit --quiet"]},{"cell_type":"code","execution_count":2,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":87592,"status":"ok","timestamp":1651381389853,"user":{"displayName":"Shwetanshu Sood","userId":"05007702121445912457"},"user_tz":-330},"id":"8WafUKkV-EFD","outputId":"38d5fdbe-49f1-435a-f809-c21681969172"},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":24,"status":"ok","timestamp":1651381389855,"user":{"displayName":"Shwetanshu Sood","userId":"05007702121445912457"},"user_tz":-330},"id":"v7pjq2eft1FK","outputId":"1809cbb2-0537-407f-9ef4-189a6addf375"},"outputs":[{"output_type":"stream","name":"stdout","text":["Writing app.py\n"]}],"source":["%%writefile app.py\n","import tensorflow as tf\n","import streamlit as st\n","from tensorflow import keras\n","import numpy as np\n","from PIL import Image\n","import requests\n","from io import BytesIO\n","\n","st.set_option('deprecation.showfileUploaderEncoding', False)\n","st.title(\"Image Classifier - 4 Categories! : Dogs, Cats, Fishes and Flowers\")\n","\n","@st.cache(allow_output_mutation = True)\n","def load_model():\n","  model = keras.models.load_model('/content/drive/MyDrive/AI_MAJOR/xception_model.hdf5')\n","  return model\n","\n","with st.spinner('Loading Model into memory......'):\n","  model = load_model()\n","\n","classes = ['cat', 'dog', 'fish', 'flower']\n","\n","def scale(image):\n","  image = tf.cast(image, tf.float32)\n","  image /= 255.0\n","\n","  return tf.image.resize(image, [224,224])\n","\n","def decode_img(image):\n","  img = tf.image.decode_jpeg(image, channels = 3)\n","  img = scale(img)\n","  return np.expand_dims(img, axis=0)\n","\n","upload = st.text_input(\"Enter the URL to classify....\",'https://thumbs.dreamstime.com/b/tench-fish-fishing-isolated-white-26542643.jpg')\n","if upload is not None:\n","  content = requests.get(upload).content\n","\n","  st.write(\"Predicted Class: \")\n","  with st.spinner(\"Classifying..... \"):\n","    label = np.argmax(model.predict(decode_img(content)), axis = 1)\n","    st.write(classes[label[0]])\n","  st.write(\"\")\n","  image = Image.open(BytesIO(content))\n","  st.image(image , caption = 'Classfying given Image', use_column_width = True)"]},{"cell_type":"code","execution_count":4,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"0iKkbj4zvf55","executionInfo":{"status":"ok","timestamp":1651381929988,"user_tz":-330,"elapsed":418277,"user":{"displayName":"Shwetanshu Sood","userId":"05007702121445912457"}},"outputId":"75ff8fb5-6b8b-44c2-cc53-93755a78499b"},"outputs":[{"output_type":"stream","name":"stdout","text":["2022-05-01 05:03:09.394 INFO    numexpr.utils: NumExpr defaulting to 2 threads.\n","\u001b[0m\n","\u001b[34m\u001b[1m  You can now view your Streamlit app in your browser.\u001b[0m\n","\u001b[0m\n","\u001b[34m  Network URL: \u001b[0m\u001b[1mhttp://172.28.0.2:8501\u001b[0m\n","\u001b[34m  External URL: \u001b[0m\u001b[1mhttp://34.125.1.194:8501\u001b[0m\n","\u001b[0m\n","\u001b[K\u001b[?25hnpx: installed 22 in 5.138s\n","your url is: https://bitter-shoes-teach-34-125-1-194.loca.lt\n","2022-05-01 05:03:35.660489: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected\n","2022-05-01 05:04:00.826 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","2022-05-01 05:06:46.120 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 39, in <module>\n","    label = np.argmax(model.predict(decode_img(content)), axis = 1)\n","  File \"/content/app.py\", line 29, in decode_img\n","    img = tf.image.decode_jpeg(image, channels = 3)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1175, in decode_jpeg\n","    name=name, ctx=_ctx)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1245, in decode_jpeg_eager_fallback\n","    attrs=_attrs, ctx=ctx, name=name)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py\", line 55, in quick_execute\n","    inputs, attrs, num_outputs)\n","tensorflow.python.framework.errors_impl.InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required. [Op:DecodeJpeg]\n","\n","2022-05-01 05:06:56.123 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","2022-05-01 05:07:34.967 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 39, in <module>\n","    label = np.argmax(model.predict(decode_img(content)), axis = 1)\n","  File \"/content/app.py\", line 29, in decode_img\n","    img = tf.image.decode_jpeg(image, channels = 3)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1175, in decode_jpeg\n","    name=name, ctx=_ctx)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1245, in decode_jpeg_eager_fallback\n","    attrs=_attrs, ctx=ctx, name=name)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py\", line 55, in quick_execute\n","    inputs, attrs, num_outputs)\n","tensorflow.python.framework.errors_impl.InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required. [Op:DecodeJpeg]\n","\n","2022-05-01 05:07:39.743 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","2022-05-01 05:08:27.755 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","2022-05-01 05:09:46.726 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 39, in <module>\n","    label = np.argmax(model.predict(decode_img(content)), axis = 1)\n","  File \"/content/app.py\", line 29, in decode_img\n","    img = tf.image.decode_jpeg(image, channels = 3)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1175, in decode_jpeg\n","    name=name, ctx=_ctx)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_image_ops.py\", line 1245, in decode_jpeg_eager_fallback\n","    attrs=_attrs, ctx=ctx, name=name)\n","  File \"/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py\", line 55, in quick_execute\n","    inputs, attrs, num_outputs)\n","tensorflow.python.framework.errors_impl.InvalidArgumentError: Unknown image file format. One of JPEG, PNG, GIF, BMP required. [Op:DecodeJpeg]\n","\n","2022-05-01 05:10:09.210 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","2022-05-01 05:10:35.415 Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.7/dist-packages/streamlit/scriptrunner/script_runner.py\", line 443, in _run_script\n","    exec(code, module.__dict__)\n","  File \"/content/app.py\", line 35, in <module>\n","    content = requests.get(upload).content\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 76, in get\n","    return request('get', url, params=params, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/api.py\", line 61, in request\n","    return session.request(method=method, url=url, **kwargs)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 516, in request\n","    prep = self.prepare_request(req)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/sessions.py\", line 459, in prepare_request\n","    hooks=merge_hooks(request.hooks, self.hooks),\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 314, in prepare\n","    self.prepare_url(url, params)\n","  File \"/usr/local/lib/python3.7/dist-packages/requests/models.py\", line 388, in prepare_url\n","    raise MissingSchema(error)\n","requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?\n","\n","\u001b[34m  Stopping...\u001b[0m\n","^C\n"]}],"source":["!streamlit run app.py & npx localtunnel --port 8501"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"u8pB4EktyxPs"},"outputs":[],"source":[""]}],"metadata":{"colab":{"collapsed_sections":[],"name":"Streamlit.ipynb","provenance":[],"authorship_tag":"ABX9TyMm6jBRNR9gsOcm1ZVLD3qz"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}